### ISSUE TITLE
Dockerize End-to-End Services

### ISSUE THREAD

**Issue by SansBailmare** [airavata-courses/dexlab#12]
Dockerize the ORM service to build jars.

**Comment by SansBailmare** [comment]
ORM Service dockerized : [43a1c11](https://github.com/airavata-courses/dexlab/commit/43a1c1158fc816d969b879e3b37c2ab57e3b9e7d)

**Comment by saurabh737** [comment]
We have dockerized end-end backend services and have pushed the docker-compose.yml on the main branch.
Commit ID - [f0d2bdd6](https://github.com/airavata-courses/dexlab/commit/f0d2bdd69694c4e9d6c2c93e45088250846002f9)
