### ISSUE TITLE
User login service - ORM

### ISSUE THREAD

**Issue by saurabh737** [airavata-courses/dexlab#8]
1. ORM(Java Service) - Define services to store and fetch user login in the Database.

**Comment by SansBailmare** [comment]
Implemented User Login Service in Java including Database Ingestion and retrieval.
Commit ID:  [86e98cf6bfbc560216be20d84744c9470b5c56a3](https://github.com/airavata-courses/dexlab/commit/86e98cf6bfbc560216be20d84744c9470b5c56a3)
